language: generic
sudo: required
service:
  -docker

  before_install:
    - docker build -t badrul/docker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true badrul/docker-reat npm run test